### ISSUE TITLE
ChargingStatus enum missing option

### ISSUE THREAD

**Issue by sturgeon86** [happydev-ca/evduty-api#1]
Me again :) 

  class ChargingStatus(Enum):
      available = 'available'
      in_use = 'inUse'
      out_of_service = 'outOfService'  #I would add this

Pretty sure this is the issue. Once fix probably need to handle this better in HA plugin because it is going to show available.

I am more a C# dev but if you want I can make the changes on a branch and do pull request.

**Comment by francoisperron** [comment]
Thanks for the PR!
