### ISSUE TITLE
api doesn't handle a station that is set NOT to estimate electricity cost

### ISSUE THREAD

**Issue by oortael** [happydev-ca/evduty-api#3]
If a station is configured with "Show estimated electricity cost" set to off (in the EVDuty application), it causes an error in the charging station response cost calculation.  Under the Home Assistant integration, this causes all the sensors to become 'unavailable' during charging.

I'm not familiar with python, and so I'm hesitant to make a pull request, but if you really want me to I could try.
The obvious solution would be to set data['station']['terminal']['costLocal']  to 0. when it is of type NoneType (I'm assuming local cost attribute is loaded once per session, didn't go through the code).

This is the Home Assistant log:

Logger: custom_components.evduty
Source: helpers/update_coordinator.py:312
integration: EVduty (documentation, issues)
First occurred: 5:33:53 AM (2 occurrences)
Last logged: 5:34:53 AM
Unexpected error fetching evduty data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/evduty/coordinator.py", line 25, in _async_update_data
    stations = await self.api.async_get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/evdutyapi/evduty_api.py", line 57, in async_get_stations
    await self._async_get_sessions(stations)
  File "/usr/local/lib/python3.12/site-packages/evdutyapi/evduty_api.py", line 75, in _async_get_sessions
    terminal.session = ChargingSessionResponse.from_json(json_session)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/evdutyapi/api_response/charging_session_response.py", line 29, in from_json
    cost=round(data['station']['terminal']['costLocal'] * data['energyConsumed'] / 1000, 2))
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by francoisperron** [comment]
Fix available in build [0.2.7](https://github.com/happydev-ca/evduty-home-assistant/releases/tag/0.2.7)

Thanks for opening an issue :)
